// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD58W3vqSBX4_0QJgC3Qx76wjRtDgoWZfQ',
    appId: '1:1036885997348:android:84c9d41b4c6667660725b1',
    messagingSenderId: '1036885997348',
    projectId: 'withcenter-project',
    storageBucket: 'withcenter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5y0hZIYa4qAJ6WgDj4C8zexGpFYEM_Vg',
    appId: '1:1036885997348:ios:5084f660c51ad9ca0725b1',
    messagingSenderId: '1036885997348',
    projectId: 'withcenter-project',
    storageBucket: 'withcenter-project.appspot.com',
    androidClientId: '1036885997348-6vosrjqhd1haic2sl736c6e9i85q6feb.apps.googleusercontent.com',
    iosClientId: '1036885997348-ng1jqh050esqh58to3aumu4dk958i53j.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );
}
